- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup.yaml

- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: javasetup.yaml

- name: install mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - mysql
  - python3-PyMySQL


- name: import data into mysql 
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: mysql.daws86s-akhil.shop
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml