- name: install nginx
  hosts: catalogue
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.package:
    - name: nginx
      state: latest
  - name: start service
    ansible.builtin.service:
    - name: nginx
      state: started 
      enabled: yes