- name: filters # functions are nothing but filters in ansible
  hosts: local
  connection: local
  become: yes
  vars:
    Tech: DevOps, Linux, Shell, Ansible
    tags:
      Application: payment
      Environment: dev
    Listtags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Ramesh') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "Technologies are {{ Tech | split(',') }}"

# Here map and dictionary both are same
  - name: convert Dictionaries into List
    ansible.builtin.debug:
      msg: "List {{ tags | dict2items }}"

  - name: Convert List to Dict
    ansible.builtin.debug:
      msg: "Map of items {{ Listtags | items2dict }}"

  - name: Formatting data from YAML to JSON
    ansible.builtin.set_fact:
      app_output: "{{ lookup('file', 'app.yaml') | from_yaml }}"

  - name: print output
    ansible.builtin.debug:
      msg: "{{ app_output }}"

