- name: disable nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove default content
  ansible.builtin.command: rm -rf /usr/share/nginx/html/* 

- name: Download frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: unzip frontend
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy config file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: restart
  ansible.builtin.service:
    name: nginx
    state: restarted