- name: copy service file
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon reload

- name: relaod, enable and start service 
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: true
