- name: copy mongo.repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: installed

- name: Start and enable service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: replace listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: reload daemon
  ansible.builtin.service:
    name: mongod
    state: restarted